spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?createDatabaseIfNotExist=true
    username: root
    password: 1729
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8082
  servlet:
    context-path: /warehouse

spring.application.name: warehouse
